"""Shared defaults for pose dataset preparation (run from repo root)."""

from __future__ import annotations

from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]

DEFAULT_VIDEOS_DIR = _REPO_ROOT / "videos"
DEFAULT_FRAMES_DIR = _REPO_ROOT / "data" / "pose" / "frames"
DEFAULT_OUTPUT_ROOT = _REPO_ROOT / "data" / "pose"
DEFAULT_LABELS_ROOT = _REPO_ROOT / "data" / "pose" / "labels"

# COCO-17 indices kept for upper-body desk POV (matches fatigue_pipeline.constants).
UPPER_BODY_KPT_INDICES = (0, 3, 4, 5, 6)
POSE_PERSON_CONF = 0.5
POSE_MIN_KPT_CONF = 0.3

DEFAULT_BASE_WEIGHTS = "yolo11n-pose.pt"

DATASET_YAML_TEMPLATE = """\
# YOLO11n-pose retraining - 5-kpt upper-body subset.
# Generated by scripts/labelling/pose/pseudo_label.py

path: {path}
train: images/train
val: images/val
test: images/test

kpt_shape: [5, 3]
flip_idx: [0, 2, 1, 4, 3]

skeleton:
  - [0, 1]
  - [0, 2]
  - [3, 4]
  - [0, 3]
  - [0, 4]

names:
  0: person
"""
